services:

  mysql-dock:
    image: mysql:8
    container_name: mysql-dock
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: client_bd
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 3

  discovery-service:
    build: ./discovery-service
    container_name: discovery-dock
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8761/actuator/health" ]
      interval:  10s
      retries:  4
  config-service:
    build: ./config-service
    container_name: config-dock
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
    depends_on:
      discovery-service:
        condition:  service_healthy
  client-service:
    build: ./client-service
    container_name: client-dock
    ports:
      - '9091:9091'
    expose:
      - '9091'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9091/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-dock:3306/client_bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      config-service:
        condition: service_healthy
      mysql-dock:
        condition: service_healthy

  offrevol-service:
    build: ./offrevol-service
    container_name: offreVol-dock
    ports:
      - '9092:9092'
    expose:
      - '9092'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9092/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-dock:3306/vol_bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      config-service:
        condition: service_healthy
      mysql-dock:
        condition: service_healthy

  reservation-service:
    build: ./reservation-service
    container_name: reservation-dock
    ports:
      - '9093:9093'
    expose:
      - '9093'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9093/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-dock:3306/reservation_bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      config-service:
        condition: service_healthy
      client-service:
        condition: service_healthy
      offrevol-service:
        condition: service_healthy
      mysql-dock:
        condition: service_healthy

  supportclient-microservice:
    build: ./supportclient-service
    container_name: supportClient-dock
    ports:
      - '9094:9094'
    expose:
      - '9094'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9094/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-dock:3306/stickets_bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      reservation-service:
        condition: service_healthy
      mysql-dock:
        condition: service_healthy

  gateway-service:
    build: ./gateway-service
    container_name: gateway-dock
    ports:
      - '8888:8888'
    expose:
      - '8888'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8888/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      supportclient-microservice:
        condition: service_healthy

volumes:
  mysql-data: